#!/bin/sh
########################################################################
#                                                                      #
# This is a drop-in replacement for the regular load plugin.           #
# It adds a new "load15" field for 15 minute load average data.        #
#                                                                      #
# Source of this fork: node.d.linux/load.in                            #
# Modified version by: Christian Schrötter <cs@fnx.li>                 #
# License: GNU General Public License, version 2                       #
#                                                                      #
########################################################################

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]
then echo no; exit 0; fi

if [ "$1" = "config" ]
then
	echo 'graph_title Load average'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel load'
	echo 'graph_scale no'
	echo 'graph_category system'
	echo 'graph_info The load average of the machine describes how many processes are in the run-queue (scheduled to run "immediately").'

	echo 'load.label load (5m)'
	echo 'load.info 5 minute load average'
	print_warning load
	print_critical load

	echo 'load15.label load (15m)'
	echo 'load15.info 15 minute load average'
	print_warning load15
	print_critical load15

	exit 0
fi

echo -n "load.value "
cut -f2 -d' ' < /proc/loadavg

echo -n "load15.value "
cut -f3 -d' ' < /proc/loadavg
